apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actualbudget
resources:
  - namespace.yaml
  - secret.yaml
  - helm.yaml
  - httproute.yaml
  - schedule-notifier/ # enable this after setting up actualbudget and ntfy and adding Vault secrets
