apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - external-secrets/flux.yaml
  - external-dns/flux.yaml
  - cert-manager/flux.yaml
  - cert-manager/issuer/flux.yaml
  - dex/flux.yaml
  - grafana/flux.yaml
  - longhorn/flux.yaml
  # - lychee/flux.yaml
  - kube-prometheus-stack/flux.yaml
  # we don't deploy Teleport yet, will consider Tailscale
  # - teleport/flux.yaml
  - metrics-server/flux.yaml
  - fluxcd-addons/flux.yaml
  # - s3-proxy/flux.yaml
  - gatewayapi-crds/flux.yaml
  - envoy-gateway/flux.yaml
  - envoyproxy/flux.yaml
  - actualbudget/flux.yaml
  - n8n/flux.yaml
  - bagisto/flux.yaml
